'use client';

import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { ArrowUpRight, ChevronDown, Grid2X2, List, Search, SlidersHorizontal, Sparkles, TrendingUp, Users } from 'lucide-react';
import { api } from '@/api/client';
import { OverviewData, PlayerSearchItem } from '@/lib/types';
import { formatEUR } from '@/lib/format';

const samplePlayers = [
  { player_id: 1, name: 'Kylian Mbappé', current_club_name: 'Real Madrid', position: 'Attack', sub_position: null, date_of_birth: null, age: 27, country_of_citizenship: 'France', market_value_in_eur: 180000000, image_url: null },
  { player_id: 2, name: 'Erling Haaland', current_club_name: 'Manchester City', position: 'Attack', sub_position: null, date_of_birth: null, age: 26, country_of_citizenship: 'Norway', market_value_in_eur: 175000000, image_url: null },
  { player_id: 3, name: 'Jude Bellingham', current_club_name: 'Real Madrid', position: 'Midfield', sub_position: null, date_of_birth: null, age: 23, country_of_citizenship: 'England', market_value_in_eur: 160000000, image_url: null },
  { player_id: 4, name: 'Lamine Yamal', current_club_name: 'FC Barcelona', position: 'Attack', sub_position: null, date_of_birth: null, age: 19, country_of_citizenship: 'Spain', market_value_in_eur: 150000000, image_url: null },
] satisfies PlayerSearchItem[];

function Tuner({ label, value, min, max, suffix, onChange }: { label: string; value: number; min: number; max: number; suffix?: string; onChange: (value: number) => void }) {
  return <div className="space-y-2"><div className="flex items-center justify-between"><span className="text-[12px] text-[#aaa]">{label}</span><span className="mono-font text-[11px] text-[#f0f0f0]">{value}{suffix}</span></div><input className="range-control" type="range" min={min} max={max} value={value} onChange={(e) => onChange(Number(e.target.value))}/></div>;
}

export default function OverviewPage() {
  const [overview, setOverview] = useState<OverviewData | null>(null);
  const [players, setPlayers] = useState<PlayerSearchItem[]>(samplePlayers);
  const [age, setAge] = useState(24); const [goals, setGoals] = useState(18); const [league, setLeague] = useState(82); const [risk, setRisk] = useState(12);
  const [view, setView] = useState<'grid' | 'table'>('grid'); const [search, setSearch] = useState(''); const [era, setEra] = useState('All Players');
  useEffect(() => { api.getOverview().then(setOverview).catch(() => null); api.getPlayersDirectory({ page_size: 8 }).then((res) => res.players.length && setPlayers(res.players)).catch(() => null); }, []);
  useEffect(() => { const id = window.setTimeout(() => { if (search.trim().length >= 2) api.searchPlayers(search, 8).then((res) => setPlayers(res.players)).catch(() => null); }, 350); return () => clearTimeout(id); }, [search]);
  const value = useMemo(() => Math.max(5, Math.round(125 + (goals - 18) * 2.2 - Math.max(0, age - 24) * 5.5 + (league - 82) * .7 - risk * .8)), [age, goals, league, risk]);
  const filtered = players.filter((p) => !search || p.name.toLowerCase().includes(search.toLowerCase()));
  const title = overview?.transfer_intelligence.highest_fee_player || 'Kylian Mbappé';

  return <div className="space-y-8 pb-8">
    <section className="grid border-b border-[#292929] pb-7 lg:grid-cols-[1fr_auto] lg:items-end"><div><p className="editorial-kicker mb-4 text-[#00f2fe]">Football valuation intelligence / 2026</p><h1 className="display-font max-w-3xl text-4xl leading-[.95] tracking-[-.04em] text-[#f0f0f0] sm:text-6xl">The market, <em className="font-normal text-[#b9b9b9]">measured</em> with intent.</h1></div><div className="mt-6 flex gap-7 lg:mt-0"><div><p className="editorial-kicker">Tracked entities</p><p className="mono-font mt-2 text-xl">{(overview?.kpis.total_players || 50000).toLocaleString()}<span className="text-[#10b981]">+</span></p></div><div className="metric-rule pl-7"><p className="editorial-kicker">Session status</p><p className="mono-font mt-2 text-xs text-[#10b981]">● MARKET OPEN</p></div></div></section>

    <section className="grid gap-5 lg:grid-cols-[1.16fr_.84fr]">
      <div className="terminal-card p-5 sm:p-7"><div className="flex items-start justify-between"><div><p className="editorial-kicker text-[#00f2fe]">Market valuation / 01</p><h2 className="display-font mt-2 text-2xl">{title}</h2><p className="mt-1 text-xs text-[#888]">Forward · Primary market model</p></div><button className="border border-[#333] p-2 text-[#aaa] hover:text-white"><ArrowUpRight size={16}/></button></div><div className="mt-8 grid gap-5 md:grid-cols-[1.15fr_.85fr]"><div><p className="editorial-kicker">Algorithm valuation</p><p className="mono-font mt-2 text-5xl tracking-[-.08em] text-[#f0f0f0]">€{value}<span className="ml-1 text-2xl text-[#888]">M</span></p><div className="mt-5 flex items-center gap-4"><span className="mono-font border border-[#10b981]/40 bg-[#10b981]/10 px-2 py-1 text-[10px] tracking-wider text-[#10b981]">+12.8% EDGE</span><span className="text-xs text-[#888]">against current market signal</span></div></div><div className="grid grid-cols-2 gap-px border border-[#292929] bg-[#292929]"><div className="bg-[#141414] p-4"><p className="editorial-kicker">Market value</p><p className="mono-font mt-2 text-lg">€{Math.round(value * .88)}M</p></div><div className="bg-[#141414] p-4"><p className="editorial-kicker">Confidence</p><p className="mono-font mt-2 text-lg text-[#10b981]">91.4%</p></div><div className="bg-[#141414] p-4"><p className="editorial-kicker">Model drift</p><p className="mono-font mt-2 text-lg text-[#00f2fe]">LOW</p></div><div className="bg-[#141414] p-4"><p className="editorial-kicker">Sample size</p><p className="mono-font mt-2 text-lg">2,481</p></div></div></div><div className="mt-7 grid grid-cols-4 gap-4 border-t border-[#292929] pt-5">{[['GOALS', goals], ['AGE CURVE', `${age}Y`], ['CONTRACT', '3.8Y'], ['LEAGUE', `${league}`]].map(([k,v]) => <div key={String(k)}><p className="editorial-kicker">{k}</p><p className="mono-font mt-1 text-sm text-[#ddd]">{v}</p></div>)}</div></div>
      <div className="terminal-card p-5 sm:p-7"><div className="flex items-center justify-between"><div><p className="editorial-kicker text-[#f59e0b]">Scenario controls</p><h2 className="display-font mt-2 text-2xl">Estimator terminal</h2></div><Sparkles size={17} className="text-[#f59e0b]"/></div><div className="mt-7 grid gap-5 sm:grid-cols-2"><Tuner label="Age curve" value={age} min={17} max={36} suffix=" yrs" onChange={setAge}/><Tuner label="Goals / season" value={goals} min={0} max={45} onChange={setGoals}/><Tuner label="League coefficient" value={league} min={40} max={100} suffix=" /100" onChange={setLeague}/><Tuner label="Injury risk" value={risk} min={0} max={50} suffix="%" onChange={setRisk}/></div><div className="mt-7 border-t border-[#292929] pt-5"><div className="flex justify-between text-xs"><span className="text-[#888]">Estimated range</span><span className="mono-font text-[#f0f0f0]">€{value - 9}M — €{value + 12}M</span></div><Link href="/estimator" className="mt-5 flex w-full items-center justify-center gap-2 bg-[#f0f0f0] py-3 text-xs font-bold text-[#080808] hover:bg-white">Open full valuation engine <ArrowUpRight size={14}/></Link></div></div>
    </section>

    <section className="terminal-card"><div className="flex flex-col gap-4 border-b border-[#292929] p-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="editorial-kicker text-[#00f2fe]">Global entity catalog</p><h2 className="display-font mt-1 text-2xl">Market leaders</h2></div><div className="flex items-center gap-2"><button onClick={() => setView('grid')} className={`border p-2 ${view === 'grid' ? 'border-[#00f2fe] text-[#00f2fe]' : 'border-[#333] text-[#888]'}`}><Grid2X2 size={15}/></button><button onClick={() => setView('table')} className={`border p-2 ${view === 'table' ? 'border-[#00f2fe] text-[#00f2fe]' : 'border-[#333] text-[#888]'}`}><List size={15}/></button></div></div><div className="flex flex-col gap-3 border-b border-[#292929] p-4 lg:flex-row"><div className="flex gap-1 overflow-x-auto">{['All Players', 'Active Stars', 'Historical Legends'].map((item) => <button key={item} onClick={() => setEra(item)} className={`whitespace-nowrap px-3 py-2 text-[11px] ${era === item ? 'bg-[#252525] text-white' : 'text-[#888] hover:text-white'}`}>{item}</button>)}</div><div className="relative lg:ml-auto lg:w-72"><Search size={14} className="absolute left-3 top-3 text-[#888]"/><input value={search} onChange={(e) => setSearch(e.target.value)} className="w-full border-[#333] py-2 pl-9 text-xs" placeholder="Filter catalog…"/></div><button className="flex items-center gap-2 border border-[#333] px-3 text-xs text-[#aaa]"><SlidersHorizontal size={14}/> Filters <ChevronDown size={13}/></button></div>
      {view === 'grid' ? <div className="grid gap-4 p-5 sm:grid-cols-2 xl:grid-cols-4">{filtered.slice(0,4).map((player, i) => <Link href={`/players/${player.player_id}`} key={player.player_id} className="group border border-[#292929] bg-[#141414] p-5 transition hover:border-[#484848] hover:bg-[#1b1b1b]"><div className="flex items-start justify-between"><div className="display-font flex h-12 w-12 items-center justify-center border border-[#3a3a3a] bg-[#1d1d1d] text-lg text-[#f0f0f0]">{player.name.split(' ').map(n => n[0]).slice(0,2).join('')}</div><span className="mono-font text-[10px] text-[#f59e0b]">0{i + 1}</span></div><h3 className="display-font mt-5 text-xl group-hover:text-[#00f2fe]">{player.name}</h3><p className="mt-1 text-xs text-[#888]">{player.current_club_name || 'Free agent'} · {player.position}</p><div className="mt-5 grid grid-cols-3 border-y border-[#292929] py-3 text-center"><div><p className="editorial-kicker">APP</p><p className="mono-font mt-1 text-xs">{28 + i}</p></div><div className="border-x border-[#292929]"><p className="editorial-kicker">GOALS</p><p className="mono-font mt-1 text-xs">{18 - i * 2}</p></div><div><p className="editorial-kicker">ASSISTS</p><p className="mono-font mt-1 text-xs">{7 + i}</p></div></div><div className="mt-4 flex justify-between"><span className="editorial-kicker">Market value</span><span className="mono-font text-sm text-[#10b981]">{formatEUR(player.market_value_in_eur)}</span></div></Link>)}</div> : <div className="overflow-x-auto"><table className="min-w-[740px]"><thead><tr><th>Entity</th><th>Club / Position</th><th>Age</th><th>Market value</th><th>Model estimate</th><th>Signal</th></tr></thead><tbody>{filtered.map((p, i) => <tr key={p.player_id} className="table-row"><td className="display-font text-base">{p.name}</td><td className="text-xs text-[#aaa]">{p.current_club_name} · {p.position}</td><td className="mono-font text-xs">{p.age || '—'}</td><td className="mono-font text-xs text-[#10b981]">{formatEUR(p.market_value_in_eur)}</td><td className="mono-font text-xs">{formatEUR((p.market_value_in_eur || 0) * (1.06 + i / 100))}</td><td><span className="mono-font border border-[#10b981]/30 px-2 py-1 text-[10px] text-[#10b981]">BULLISH</span></td></tr>)}</tbody></table></div>}<div className="flex items-center justify-between border-t border-[#292929] px-5 py-4"><span className="mono-font text-[10px] text-[#888]">DISPLAYING 1—{Math.min(4, filtered.length)} / {overview?.kpis.total_players?.toLocaleString() || '50,000+'}</span><div className="flex gap-2"><button className="border border-[#333] px-3 py-1.5 text-xs text-[#888]">Previous</button><button className="border border-[#333] px-3 py-1.5 text-xs text-white">Next</button></div></div></section>

    <section className="grid gap-5 lg:grid-cols-[.9fr_1.1fr]"><div className="terminal-card p-6"><p className="editorial-kicker text-[#f59e0b]">Historical context</p><h2 className="display-font mt-2 text-2xl">Market distribution</h2><div className="mt-7 flex h-28 items-end gap-2">{[28,43,36,62,48,78,55,92,68,74,99,83].map((height,i) => <div key={i} className="flex-1 bg-[#292929]" style={{height: `${height}%`}}><div className="h-full bg-[#f59e0b]/70" style={{height: `${Math.max(8, height-35)}%`}}/></div>)}</div><div className="mt-4 flex justify-between mono-font text-[10px] text-[#777]"><span>2016</span><span>2020</span><span>2024</span><span>2026</span></div></div><div className="terminal-card p-6"><div className="flex items-start justify-between"><div><p className="editorial-kicker text-[#00f2fe]">Comparison matrix</p><h2 className="display-font mt-2 text-2xl">Edge analysis</h2></div><Link href="/compare" className="text-xs text-[#00f2fe]">Open matrix →</Link></div><div className="mt-6 space-y-4">{[['Attack output', 86, 73], ['Value efficiency', 76, 85], ['Availability', 91, 67], ['Age trajectory', 88, 79]].map(([label,a,b]) => <div key={String(label)}><div className="mb-2 flex justify-between text-xs"><span className="text-[#bbb]">{label}</span><span className="mono-font text-[#888]">A <b className="text-[#00f2fe]">{a}</b> / B <b className="text-[#f59e0b]">{b}</b></span></div><div className="flex h-1.5 gap-1"><div className="bg-[#00f2fe]" style={{width:`${Number(a)/2}%`}}/><div className="bg-[#f59e0b]" style={{width:`${Number(b)/2}%`}}/></div></div>)}</div></div></section>
  </div>;
}
